### ISSUE TITLE
add link to original files?

### ISSUE THREAD

**Issue by LFSaw** [gwf/CBofN#1]
Hello :) 
Many thanks for the book and the code examples! I was very happy to see that they compile on my current OSX machine, although the X11 (XQuartz) windows keep on turning up black :/ ... 

I was wondering, if you'd like to include a link to the original webpage:
https://mitpress.mit.edu/sites/default/files/titles/content/cbnhtml/home.html

Since it also holds links to the java versions of some (?) of the code you wrote.

**Comment by gwf** [comment]
Done.  The link that had been there (but is now no longer working) was supposed to be the "permanent" redirect for the mitpress site.  But after nearly 20 years of being hosted there, it's not surprising that the forward would break.  Thanks for pointing out the problem.

**Comment by LFSaw** [comment]
so much for "permanent"... book is still relevant, though, thanks for that!
